---
- hosts: test
  remote_user: root
  vars:
    otrs_user_pass: $6$U4/4vGhOOkdL15431$fS5eKM.aiZnhMod4KGogFbqPCpsj2gxyeSNdWxQ3WyhmuFE36ZpzZCGxE//y2TzG0v1/6MxzrWt8k5fyfQ181

  tasks:

  - name: Stopping the Firewall service
    service: name=firewalld state=stopped enabled=no

  - selinux:
      state: disabled

  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present

  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      state: present

  - name: Installing Apache and Mod_Perl
    yum: state=latest name={{ item }}
    with_items:
    - httpd
    - httpd-devel
    - mod_perl

  - name: Chkconfig ON
    shell: /sbin/chkconfig httpd on

  - name: Instalando o Banco de Dados
    yum: state=latest name={{ item }}
    with_items:
    - mariadb
    - mariadb-server

  - name: Chkconfig ON
    shell: /sbin/chkconfig mariadb on

  - name: Starting the Database
    service: name=mariadb state=started enabled=yes

  - name: Removing the my.cnf file
    shell: rm -rf /etc/my.cnf

  - name: Creating the my.cnf file
    file:
      path: /etc/my.cnf
      state: touch
      mode: "u+rw,g-wx,o-wx"

  - name: Adding rows in the my.cnf file
    lineinfile:
      dest: /etc/my.cnf
      line: '{{ item }}'
    with_items:
      - '[mysqld]'
      - 'socket=/var/lib/mysql/mysql.sock'
      - 'max_allowed_packet = 128M'
      - 'query_cache_size = 32M'
      - 'innodb_log_file_size = 256M'
      - 'innodb_fast_shutdown=0'
      - ' '
      - '# Disabling symbolic-links is recommended to prevent assorted security risks'
      - 'symbolic-links=0'
      - '  '
      - '# Settings user and group are ignored when systemd is used.'
      - '# If you need to run mysqld under a different user or group,'
      - '# customize your systemd unit file for mariadb according to the'
      - '# instructions in http://fedoraproject.org/wiki/Systemd'
      - '   '
      - '[mysqld_safe]'
      - 'log-error=/var/log/mariadb/mariadb.log'
      - 'pid-file=/var/run/mariadb/mariadb.pid'
      - '    '
      - '# include all files from the config directory'
      - '!includedir /etc/my.cnf.d'

  - name: Stopping the Database
    service: name=mariadb state=stopped

  - name: Deleting logfile0 file
    shell: rm -rf /var/lib/mysql/lib_logfile0

  - name: Deleting logfile1 file
    shell: rm -rf /var/lib/mysql/lib_logfile1

  - name:  Starting the database again
    service: name=mariadb state=started

  - name: Installing Wget and bzip2
    yum: state=latest name={{ item }}
    with_items:
    - wget
    - bzip2

  - name: Downloading OTRS
    shell: wget -c -P /opt/  https://ftp.otrs.org/pub/otrs/otrs-6.0.2.tar.bz2

  - name: Unlinking file
    shell: tar -jxpf /opt/otrs-6.0.2.tar.bz2 -C /opt/

  - name: Renaming the OTRS folder
    shell: mv /opt/otrs-6.0.2 /opt/otrs

  - name: Creating OTRS User
    user: name=otrs password={{ otrs_user_pass }} comment="OTRS User" group=apache

  - name: Installing PERL packages
    yum: state=latest name={{ item }}
    with_items:
    - "perl(ExtUtils::MakeMaker)"
    - "perl(Sys::Syslog)"
    - "perl(Archive::Tar)"
    - "perl(Archive::Zip)"
    - "perl(Crypt::Eksblowfish::Bcrypt)"
    - "perl(Crypt::SSLeay)"
    - "perl(Date::Format)"
    - "perl(DBD::Pg)"
    - "perl(Encode::HanExtra)"
    - "perl(IO::Socket::SSL)"
    - "perl(JSON::XS)"
    - "perl(Mail::IMAPClient)"
    - "perl(IO::Socket::SSL)"
    - "perl(ModPerl::Util)"
    - "perl(Net::DNS)"
    - "perl(Net::LDAP)"
    - "perl(Template)"
    - "perl(Template::Stash::XS)"
    - "perl(Text::CSV_XS)"
    - "perl(Time::Piece)"
    - "perl(XML::LibXML)"
    - "perl(XML::LibXSLT)"
    - "perl(XML::Parser)"
    - "perl(YAML::XS)"
    - "perl(DBD::ODBC)"
    - "perl(DateTime)"
    - "perl(LWP::UserAgent)"
    - "perl(Authen::NTLM)"

  - name: Copying file Config.pm
    copy:
      src: /opt/otrs/Kernel/Config.pm.dist
      dest: /opt/otrs/Kernel/Config.pm

  - name: Creating a somber link
    shell: ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/httpd/conf.d/zzz_otrs.conf

  - name: Setting permissions "otrs.SetPermissions.pl"
    shell: /opt/otrs/bin/otrs.SetPermissions.pl --web-group=apache

  - name: Enabling the Apache service
    service: name=httpd state=stopped enabled=yes

  - name: Copying Daemon file
    copy:
      src: /opt/otrs/var/cron/otrs_daemon.dist
      dest: /opt/otrs/var/cron/otrs_daemon

  - name: Starting the Cron
    shell: /opt/otrs/bin/Cron.sh start otrs

  - name: Restarting the Server
    shell: reboot
